#!/bin/bash

chmod 644 /etc/xdg/autostart/comexr-fan-control.desktop || echo "something went wrong with permissions"
chown root /usr/local/bin/comexr-fan-control
chmod u+s /usr/local/bin/comexr-fan-control
exit 0
